version: '3'
services:
 wp-service:
  build: ./press
  ports:
   - "8000:80"
  environment:
   WORDPRESS_DB_PASSWORD: student
 mysql:
  image: "mysql:5.7"
  environment:
   MYSQL_ROOT_PASSWORD: student
